#!/usr/bin/env sh

_() {
    read -p "GitHub Username: " -r USERNAME
    printf "GitHub Access token: "
    stty -echo
    read -r ACCESS_TOKEN
    stty echo
    echo
    read -p "Repository name (default: YEAR): " -r REPO_NAME
    read -p "Year (e.g. 2001): " -r YEAR
    read -p "Month (01-12, default: 10): " -r MONTH
    read -p "Day (01-31, default: 10): " -r DAY

    [ -z "$USERNAME" ] && exit 1
    [ -z "$ACCESS_TOKEN" ] && exit 1
    [ -z "$YEAR" ] && YEAR="2001"
    [ -z "$REPO_NAME" ] && REPO_NAME="$YEAR"
    [ -z "$MONTH" ] && MONTH="10"
    [ -z "$DAY" ] && DAY="10"

    [ ! -d "$REPO_NAME" ] && mkdir "$REPO_NAME"

    cd "${REPO_NAME}" || exit
    git init
    echo "# 🫡 Welcome back to ${YEAR}\n\nThis repo was generated dynamically for year ${YEAR} using [github-timetravel](https://github.com/github-timetravel/timetravel).\n\n## Usage\n- Clone this repo\n- View commit history for backdated entries\n\nGenerated by timetravel script on $(date '+%Y-%m-%d')" > README.md
    git add .
    GIT_AUTHOR_DATE="${YEAR}-${MONTH}-${DAY}T18:00:00" \
        GIT_COMMITTER_DATE="${YEAR}-${MONTH}-${DAY}T18:00:00" \
        git commit -m "${YEAR}"
    git remote add origin "https://${ACCESS_TOKEN}@github.com/${USERNAME}/${REPO_NAME}.git"
    git branch -M main
    git push -u origin main -f
    cd ..
    rm -rf "${REPO_NAME}"

    echo
    echo "Cool, check your profile now: https://github.com/${USERNAME}"
} && _

unset -f _
